/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hastanerandevusistemi;

import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Cankıvanç
 */
public class AdminHastaBilgisiEkrani extends javax.swing.JFrame {

    VeritabaniIslemleri islemler = new VeritabaniIslemleri();
    DefaultTableModel model;

    /**
     * Creates new form AdminHastaBilgisiEkrani
     */
    public AdminHastaBilgisiEkrani() {
        initComponents();
        model = (DefaultTableModel) hasta_tablosu.getModel();
        hastaTümBilgiGörüntüle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arama_cubugu = new javax.swing.JTextField();
        hasta_ad_alani = new javax.swing.JTextField();
        hasta_soyad_alani = new javax.swing.JTextField();
        hasta_kullanici_adi_alani = new javax.swing.JTextField();
        hasta_parola_alani = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasta_tablosu = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mesaj_yazisi = new javax.swing.JLabel();
        cikis_butonu = new javax.swing.JButton();
        hasta_sil_butonu = new javax.swing.JButton();
        hasta_güncelle_butonu = new javax.swing.JButton();
        hasta_ekle_butonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });

        hasta_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hasta ID", "Hasta Ad", "Hasta Soyad", "Hasta Kullanıcı Adı", "Hasta Parola"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hasta_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hasta_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(hasta_tablosu);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Arama :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Hasta Ad                 :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Hasta Soyad            :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Hasta Kullanıcı Adı     :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Hasta Parola            :");

        mesaj_yazisi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mesaj_yazisi.setForeground(new java.awt.Color(255, 51, 51));

        cikis_butonu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cikis_butonu.setText("Çıkış Yap");
        cikis_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikis_butonuActionPerformed(evt);
            }
        });

        hasta_sil_butonu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hasta_sil_butonu.setText("Hasta Sil");
        hasta_sil_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasta_sil_butonuActionPerformed(evt);
            }
        });

        hasta_güncelle_butonu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hasta_güncelle_butonu.setText("Hasta Güncelle");
        hasta_güncelle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasta_güncelle_butonuActionPerformed(evt);
            }
        });

        hasta_ekle_butonu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hasta_ekle_butonu.setText("Yeni Hasta Ekle");
        hasta_ekle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasta_ekle_butonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(arama_cubugu))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(hasta_ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(hasta_kullanici_adi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(hasta_soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(hasta_parola_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(mesaj_yazisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hasta_güncelle_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hasta_ekle_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hasta_sil_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cikis_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hasta_ekle_butonu)
                        .addGap(18, 18, 18)
                        .addComponent(hasta_güncelle_butonu))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hasta_ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hasta_soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hasta_sil_butonu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(cikis_butonu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(hasta_kullanici_adi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(hasta_parola_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased

        String ara = arama_cubugu.getText();
        dinamikAra(ara);
    }//GEN-LAST:event_arama_cubuguKeyReleased

    private void hasta_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hasta_tablosuMouseClicked
        int selectedRow = hasta_tablosu.getSelectedRow();

        hasta_ad_alani.setText(model.getValueAt(selectedRow, 1).toString());
        hasta_soyad_alani.setText(model.getValueAt(selectedRow, 2).toString());
        hasta_kullanici_adi_alani.setText(model.getValueAt(selectedRow, 3).toString());
        hasta_parola_alani.setText(model.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_hasta_tablosuMouseClicked

    private void cikis_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikis_butonuActionPerformed
        dispose();
        hasta_ad_alani.setText("");
        hasta_soyad_alani.setText("");
        hasta_kullanici_adi_alani.setText("");
        hasta_parola_alani.setText("");
        mesaj_yazisi.setText("");
    }//GEN-LAST:event_cikis_butonuActionPerformed

    private void hasta_sil_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasta_sil_butonuActionPerformed
        mesaj_yazisi.setText("");

        int selectedRow = hasta_tablosu.getSelectedRow();

        if (selectedRow == -1) {

            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("Kayıtlı hasta bulunmamaktadır...");
            } else {
                mesaj_yazisi.setText("Lütfen silinecek bir kişi seçin...");
            }
        } else {
            int hastaID = (int) model.getValueAt(selectedRow, 0);
            islemler.hastaSil(hastaID);
            hastaTümBilgiGörüntüle();
            mesaj_yazisi.setText("Hasta bilgisi başarıyla silindi...");
            hasta_ad_alani.setText("");
            hasta_soyad_alani.setText("");
            hasta_kullanici_adi_alani.setText("");
            hasta_parola_alani.setText("");
        }
    }//GEN-LAST:event_hasta_sil_butonuActionPerformed

    private void hasta_güncelle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasta_güncelle_butonuActionPerformed

        String hastaAd = hasta_ad_alani.getText();
        String hastaSoyad = hasta_soyad_alani.getText();
        String hastaKullaniciAdi = hasta_kullanici_adi_alani.getText();
        String hastaParola = hasta_parola_alani.getText();

        int selectedRow = hasta_tablosu.getSelectedRow();

        if (selectedRow == -1) {

            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("Kayıtlı hasta bulunmamaktadır...");
            } else {
                mesaj_yazisi.setText("Lütfen güncellenecek bir kişi seçin...");
            }
        } else {

            int hastaID = (int) model.getValueAt(selectedRow, 0);
            islemler.hastaGüncelle(hastaID, hastaAd, hastaSoyad, hastaKullaniciAdi, hastaParola);
            hastaTümBilgiGörüntüle();
            mesaj_yazisi.setText("Hasta bilgisi başarıyla güncellendi...");
            hasta_ad_alani.setText("");
            hasta_soyad_alani.setText("");
            hasta_kullanici_adi_alani.setText("");
            hasta_parola_alani.setText("");
        }
    }//GEN-LAST:event_hasta_güncelle_butonuActionPerformed

    private void hasta_ekle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasta_ekle_butonuActionPerformed
        mesaj_yazisi.setText("");

        String hastaAd = hasta_ad_alani.getText();
        String hastaSoyad = hasta_soyad_alani.getText();
        String hastaKullaniciAdi = hasta_kullanici_adi_alani.getText();
        String hastaParola = hasta_parola_alani.getText();

        if (hastaAd.equals("") || hastaSoyad.equals("") || hastaKullaniciAdi.equals("") || hastaParola.equals("")) {
            mesaj_yazisi.setText("Hasta eklenemedi. Lütfen bütün alanları doldurunuz...");
        } else {
            islemler.hastaEkle(hastaAd, hastaSoyad, hastaKullaniciAdi, hastaParola);
            hastaTümBilgiGörüntüle();
            mesaj_yazisi.setText("Yeni hasta eklendi...");
            hasta_ad_alani.setText("");
            hasta_soyad_alani.setText("");
            hasta_kullanici_adi_alani.setText("");
            hasta_parola_alani.setText("");
        }
    }//GEN-LAST:event_hasta_ekle_butonuActionPerformed

    public void hastaTümBilgiGörüntüle() {

        model.setRowCount(0);

        ArrayList<Hasta> hastaListe = new ArrayList<Hasta>();

        hastaListe = islemler.hastaTümBilgiGönder();

        if (hastaListe != null) {

            for (Hasta hasta : hastaListe) {

                Object[] eklenecek = {hasta.getId(), hasta.getAd(), hasta.getSoyad(), hasta.getKullaniciAdi(), hasta.getParola()};
                model.addRow(eklenecek);
            }
        }
    }

    public void dinamikAra(String ara) {

        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<DefaultTableModel>(model);

        hasta_tablosu.setRowSorter(rowSorter);

        rowSorter.setRowFilter(RowFilter.regexFilter(ara));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHastaBilgisiEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHastaBilgisiEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHastaBilgisiEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHastaBilgisiEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHastaBilgisiEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JButton cikis_butonu;
    private javax.swing.JTextField hasta_ad_alani;
    private javax.swing.JButton hasta_ekle_butonu;
    private javax.swing.JButton hasta_güncelle_butonu;
    private javax.swing.JTextField hasta_kullanici_adi_alani;
    private javax.swing.JTextField hasta_parola_alani;
    private javax.swing.JButton hasta_sil_butonu;
    private javax.swing.JTextField hasta_soyad_alani;
    private javax.swing.JTable hasta_tablosu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesaj_yazisi;
    // End of variables declaration//GEN-END:variables
}
